### ISSUE TITLE
Debug JWT token

### ISSUE THREAD

**Issue by goFrendiAsgard** [FawwazAF/ET_Market_Project#46]
https://github.com/FawwazAF/ET_Market_Project/blob/91f52798c2ca7ad4b92a532719f4622a64bff6c5/controller/deliveringController_test.go#L54

Mas @FawwazAF bagian di sini coba `error` nya dimunculkan:

```
token, err := middlewares.CreateToken(int(driver.ID))
if err != nil {
    panic(err)
}
```

**Comment by FawwazAF** [comment]
sudah dicoba, tapi masih sama errornya sih mas

**Comment by goFrendiAsgard** [comment]
Inikah errornya?
![image](https://user-images.githubusercontent.com/883662/130405571-16593419-9249-4963-a084-3f0638f5f8e9.png)

**Comment by FawwazAF** [comment]
iyaa mas itu error karena pake func extract token yang di project kemarin 
![image](https://user-images.githubusercontent.com/87788922/130412647-997037ff-b533-4a04-995a-c70147d56c8c.png)
kalau pakai function dari git yang ini https://github.com/redyapr/acp9/blob/4af5fd4948774c4d652ac380ac6ce8b903cb5a1b/middlewares/jwt.go#L21 , itu error nya seperti ini mas 
![image](https://user-images.githubusercontent.com/87788922/130412411-57ea9a1e-c3f1-4133-84b1-d29e3cebad4f.png)

jadi returnan dari func extract token nya 0, karena e.Get("user") nya nil
